### ISSUE TITLE
Wrong number of elements or type in tuple for event_flow_clear

### ISSUE THREAD

**Issue by gareging** [zeek/zeek-netcontrol#6]
Hi,
We're testing example.zeek and controller.py. 

At the startup, we get this error message:
"wrong number of elements or type in tuple for event_flow_clear"

We found out that  **not isinstance(m[1], broker.Count)** (line number 153) returns True. Could you please help us with this issue?

**Comment by jsiwek** [comment]
Using the latest master branch (of both `zeek` and `zeek-netcontrol`), if I run like:

`ryu-manager openflow/controller.py`

and

`zeek openflow/example.zeek`

I actually didn't get that same error you mentioned, but I did get others.  Maybe you are using the 2.6 version?  Or have a mismatch between the netcontrol and Bro/Zeek versions ?  e.g. it's not likely the master version of netcontrol works with Bro 2.6.

In any case, likely this code just hasn't been updated to keep up with changes in the Broker/Python API and so it's not in a working state right now.

I did spend a little time and came up with the start of a patch to at least get past the overt errors I saw in the master branches if you want to try to pursue that:

```diff
diff --git a/openflow/controller.py b/openflow/controller.py
index 058325d..77b96a7 100755
--- a/openflow/controller.py
+++ b/openflow/controller.py
@@ -5,6 +5,8 @@
 #
 # Start with ./ryu/bin/ryu-manager controller.py
 
+import datetime
+import ipaddress
 import logging
 import time
 import re
@@ -86,7 +88,7 @@ class BroController(app_manager.RyuApp):
     def start(self):
         self.epl.listen("127.0.0.1", 9999)
         self.status_subscriber = self.epl.make_status_subscriber(True)
-        self.subscriber = self.epl.make_subscriber(self.queuename)
+        self.subscriber = self.epl.make_subscriber(queuename)
 
         self.threads.append(hub.spawn(self._broker_loop))
         self.logger.info("Started broker communication...")
@@ -183,17 +185,11 @@ class BroController(app_manager.RyuApp):
         ryu.app.ofctl.api.send_msg(self, msg)
 
     def send_error(self, name, match, flow_mod, msg):
-        args = [name, match, flow_mod, msg]
-        ev = broker.zeek.Event("OpenFlow::flow_mod_failure", args)
-        m.push_back(data(name))
-        m.push_back(match)
-        m.push_back(flow_mod)
-        m.push_back(data(msg))
+        ev = broker.zeek.Event("OpenFlow::flow_mod_failure", name, match, flow_mod, msg)
         self.epl.publish(queuename, ev)
 
     def send_success(self, name, match, flow_mod, msg):
-        args = [name, match, flow_mod, msg]
-        ev = broker.zeek.Event("OpenFlow::flow_mod_success", args)
+        ev = broker.zeek.Event("OpenFlow::flow_mod_success", name, match, flow_mod, msg)
         self.epl.publish(queuename, ev)
 
     def event_flow_mod(self, m):
@@ -211,7 +207,7 @@ class BroController(app_manager.RyuApp):
 
         if dp is None:
             self.logger.error("name %s dpid %d not found for flow_mod", name, dpid)
-            self.send_error(m[2], m[3], "dpid not found")
+            self.send_error(name, m[2], m[3], "dpid not found")
             return
 
         self.dpids[dp.id] = name
@@ -431,7 +427,7 @@ class BroController(app_manager.RyuApp):
 
         rm = m
         rl = rm[9]
-        recaction = self.record_to_record(match_actions, rl.get())
+        recaction = self.record_to_record(match_actions, rl)
         rec['actions'] = recaction
 
         return rec
@@ -585,7 +581,7 @@ class BroController(app_manager.RyuApp):
             return re.sub(r'.*::', r'', tmp)
 
         if isinstance(el, list):
-            return [convertElement(ell) for ell in el];
+            return [self.convert_element(ell) for ell in el];
 
         if isinstance(el, datetime.datetime):
             return el
```

**Comment by sahilgupta221** [comment]
The initial error would be "AttributeError: 'BroController' object has no attribute 'queuename'"
This is resolved by making queuename as part of init method.
After that, you will get those error mentioned by gareging.
Did you commit to master repo?
I can see the last commit 5 days ago.
If not, please provide a link to your branch of repo so that we can checkout latest code.
Thanks for looking into the problem.
:)

**Comment by jsiwek** [comment]
I didn't commit anything into git, it's just the patch against `master` I gave above since it's likely incomplete or maybe not entirely correct (I'm not familiar enough w/ how to throughly test this code).

**Comment by jsiwek** [comment]
I pushed the patch into the `master` branch, but I'm not sure it's entirely complete since the example code likely doesn't cover all code paths, but should at least not be entirely broken now.  If you find more problems, please report back.

**Comment by 0xxon** [comment]
Closing, since this seems solved.
